version: '3'

volumes:
  react_build:
  postgres_data:
  static_volume:
  media_volume:

services:
  postgresdb:
    image: ober123/el-postgres
    environment:
      - POSTGRES_PASSWORD=Aidar191&
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  backend:
    image: ober123/el-django
    volumes:
      - ./:/usr/src/app
      - media_volume:/django/mediafiles
    depends_on:
      - postgresdb
    command: gunicorn elstep.wsgi --bind 0.0.0.0:8000 --reload
    ports:
      - "8000:8000"

  frontend:
    image: ober123/el-react
    volumes:
      - react_build:/react/build

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
      - static_volume:/usr/src/app/django/staticfiles
      - media_volume:/data/media
    depends_on:
      - backend
      - frontend
      - postgresdb
